version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    env_file: ./.env

  authenticator:
    container_name: authenticator
    build:
      context: ./authenticator
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - "3030:3030"
    depends_on:
      - postgres
      - kafka

  email-sender:
    container_name: email-sender
    build:
      context: ./email-sender
      dockerfile: ./Dockerfile
    depends_on:
      - authenticator
      - kafka

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
